In [1]:
import numpy as np

In [2]:
# Array apartir de um lista

lista1 = [1, 2, 3, 4, 5]

In [4]:
arr = np.array(lista1)

arr

array([1, 2, 3, 4, 5])

In [5]:
# Array de zeros com np.zero(n)

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
# Criando Array de numeros com sequencia

np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [7]:
np.arange(10, 20, 0.5)

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

In [9]:
# linspace

np.linspace(10, 20, 50)

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [18]:
# random   numeros float

np.random.seed(10)

np.random.rand(10)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981])

In [21]:
# random numeros int

np.random.randint(0, 50, 20)

array([16,  7, 24, 11, 17, 46,  7, 11, 28, 33, 20, 32, 24, 44,  5,  4,  7,
       24, 24, 44])

In [22]:
# array de inteiros aleatorios sem reposição

np.random.choice(np.arange(10, 101), 20, replace=False)

array([45, 95, 57, 34, 99, 14, 75, 20, 68, 17, 79, 73, 49, 30, 48, 18, 43,
       11, 77, 15])

In [24]:
# random.normal

np.random.normal(0, 1, 20)

array([-0.47067661, -0.36261508, -0.78856756,  1.2565695 , -1.20646161,
        0.28252607, -0.49924499,  0.50068795,  1.37119341, -0.712783  ,
       -0.34729674, -1.26406441,  0.68629461, -1.20170603,  0.62520081,
        0.49357305,  0.62294969, -0.40904272, -0.31779202, -0.91850011])

In [26]:
# indexação de arrays

arr = np.arange(2, 50, 3)

arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [27]:
arr[3]

11

In [28]:
arr[:4]

array([ 2,  5,  8, 11])

In [29]:
arr[5:]

array([17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [31]:
# operações com arrays

arr1 = np.random.randint(10, 50, 7)
arr2 = np.linspace(1, 10, 7)

In [32]:
print(arr1)
print(arr2)

[49 27 49 43 21 24 25]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]


In [33]:
arr1 + arr2   # soma

array([50. , 29.5, 53. , 48.5, 28. , 32.5, 35. ])

In [38]:
# Metodos

np.random.seed(42)

arr = np.random.randint(0, 500, 50)

arr

array([102, 435, 348, 270, 106,  71, 188,  20, 102, 121, 466, 214, 330,
       458,  87, 372,  99, 359, 151, 130, 149, 308, 257, 343, 491, 413,
       293, 385, 191, 443, 276, 160, 459, 313,  21, 252, 235, 344,  48,
       474,  58, 169, 475, 187, 463, 270, 189, 445, 174, 445])

In [39]:
# maior valor

arr.max()

491

In [40]:
# indice do elemento maximo

arr.argmax()

24

In [41]:
# menor valor

arr.min()

20

In [42]:
# indice do elemento minimo

arr.argmin()

7

In [43]:
# soma de todos os itens

arr.sum()

13159

In [44]:
# media dos elementos

arr.mean()

263.18

In [45]:
# desvio padrão

arr.std()

142.08654968011575

In [46]:
# trocando o tipo de dados na lista

arr.dtype

dtype('int32')

In [47]:
arr.astype(float)

array([102., 435., 348., 270., 106.,  71., 188.,  20., 102., 121., 466.,
       214., 330., 458.,  87., 372.,  99., 359., 151., 130., 149., 308.,
       257., 343., 491., 413., 293., 385., 191., 443., 276., 160., 459.,
       313.,  21., 252., 235., 344.,  48., 474.,  58., 169., 475., 187.,
       463., 270., 189., 445., 174., 445.])

In [48]:
# Matrizes

# array unidimencional (com o arange)

arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
arr.reshape((5, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [50]:
arr.reshape((2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [51]:
arr2 = np.random.randint(0, 100, 12)

arr2

array([50, 54, 63,  2, 50,  6, 20, 72, 38, 17,  3, 88])

In [54]:
Matriz2 = arr2.reshape((4, 3))

Matriz2

array([[50, 54, 63],
       [ 2, 50,  6],
       [20, 72, 38],
       [17,  3, 88]])

In [57]:
# indexando matrizes

Matriz2[3, 1]

3

In [58]:
Matriz2[:2, :2]

array([[50, 54],
       [ 2, 50]])

In [59]:
# criando matriz identidade

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [60]:
# outro exemplos de criação de matrizes

np.arange(10).reshape((5, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [61]:
np.random.randint(100, 200, (3, 3))

array([[159, 113, 108],
       [189, 152, 101],
       [183, 191, 159]])

In [63]:
# filtros

arr = np.random.randint(0, 100, 20)

arr

array([33, 73, 61, 99, 13, 94, 47, 14, 71, 77, 86, 61, 39, 84, 79, 81, 52,
       23, 25, 88])

In [65]:
arr > 50

array([False,  True,  True,  True, False,  True, False, False,  True,
        True,  True,  True, False,  True,  True,  True,  True, False,
       False,  True])

In [64]:
arr[arr>50]

array([73, 61, 99, 94, 71, 77, 86, 61, 84, 79, 81, 52, 88])

In [66]:
# condição de pares

arr % 2 == 0

array([False, False, False, False, False,  True, False,  True, False,
       False,  True, False, False,  True, False, False,  True, False,
       False,  True])

In [67]:
arr[arr % 2 == 0]

array([94, 14, 86, 84, 52, 88])

In [68]:
# condição de pares e maiores que 50

arr[(arr % 2 == 0) & (arr>50)]

array([94, 86, 84, 52, 88])

In [69]:
# condição de pares ou maiores que 50

arr[(arr % 2 == 0) | (arr>50)]

array([73, 61, 99, 94, 14, 71, 77, 86, 61, 84, 79, 81, 52, 88])